# ========================================
# FileName: environment.yml
# Date: 22 nov 2024
# Author: Ammar Mian
# Email: ammar.mian@univ-smb.fr
# GitHub: https://github.com/ammarmian
# Brief: Environment file for anotherspdnet - cpu version
# =========================================

name: anotherspdnet-cpu
channels:
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - pandas
  - ipython
  - pip:
    - git+https://github.com/ammarmian/qanat
    - git+https://github.com/geoopt/geoopt.git
    - git+https://github.com/AmmarMian/anotherspdnet
    - memory_profiler
    - watchdog
    - plotille
    - pyyaml
    - rich
    - tensorboard
    - skorch
